" Afterglow (Light) — same palette as themes/afterglow.theme.sh

let g:foreglow_label          = 'Afterglow'
let g:foreglow_background     = '#F4EEE1'
let g:foreglow_bg_alt         = '#ECE5D5'
let g:foreglow_current_line   = '#E6D6C1'
let g:foreglow_selection      = '#DFC2AA'
let g:foreglow_border         = '#CDAEA2'
let g:foreglow_foreground     = '#24163B'
let g:foreglow_foreground_dim = '#574979'
let g:foreglow_comment        = '#7A6F9B'
let g:foreglow_keyword        = '#8930A6'
let g:foreglow_string         = '#B64820'
let g:foreglow_function       = '#AE296B'
let g:foreglow_number         = '#955F0F'
let g:foreglow_class          = '#1D7187'
let g:foreglow_variable       = '#4D3781'
let g:foreglow_operator       = '#7F5893'
let g:foreglow_error          = '#B12531'
let g:foreglow_warning        = '#A25410'
let g:foreglow_success        = '#22775B'
let g:foreglow_cursor         = '#C3228E'
