" Airglow (Auroral) — same palette as themes/airglow.theme.sh

let g:foreglow_label          = 'Airglow'
let g:foreglow_background     = '#0A1A1F'
let g:foreglow_bg_alt         = '#0F2024'
let g:foreglow_current_line   = '#0F2024'
let g:foreglow_selection      = '#162E34'
let g:foreglow_border         = '#2A4A50'
let g:foreglow_foreground     = '#E0F0F5'
let g:foreglow_foreground_dim = '#7A9AA0'
let g:foreglow_comment        = '#5A8A90'
let g:foreglow_keyword        = '#2EE8C8'
let g:foreglow_string         = '#7DD8A8'
let g:foreglow_function       = '#C8A0E8'
let g:foreglow_number         = '#D4B870'
let g:foreglow_class          = '#4AA8D0'
let g:foreglow_variable       = '#8BC4D4'
let g:foreglow_operator       = '#6A9AA0'
let g:foreglow_error          = '#E87070'
let g:foreglow_warning        = '#D4B870'
let g:foreglow_success        = '#4AC878'
let g:foreglow_cursor         = '#2EE8C8'
