" Alpenglow (Rubescent) — same palette as themes/alpenglow.theme.sh

let g:foreglow_label          = 'Alpenglow'
let g:foreglow_background     = '#1A0505'
let g:foreglow_bg_alt         = '#2D0A0A'
let g:foreglow_current_line   = '#3D1212'
let g:foreglow_selection      = '#5A1E1E'
let g:foreglow_border         = '#4D1818'
let g:foreglow_foreground     = '#F5E6DC'
let g:foreglow_foreground_dim = '#C4A398'
let g:foreglow_comment        = '#8B6B6B'
let g:foreglow_keyword        = '#FF6B8A'
let g:foreglow_string         = '#FF9F6C'
let g:foreglow_function       = '#FFB3C6'
let g:foreglow_number         = '#FF7E67'
let g:foreglow_class          = '#E85D75'
let g:foreglow_variable       = '#FFA07A'
let g:foreglow_operator       = '#CC7A8E'
let g:foreglow_error          = '#FF4444'
let g:foreglow_warning        = '#FF8844'
let g:foreglow_success        = '#E85D75'
let g:foreglow_cursor         = '#FF6B9D'
