" Foreglow (Dark) — same palette as themes/foreglow.theme.sh

let g:foreglow_label          = 'Foreglow'
let g:foreglow_background     = '#161221'
let g:foreglow_bg_alt         = '#1D182A'
let g:foreglow_current_line   = '#281F3D'
let g:foreglow_selection      = '#3D2556'
let g:foreglow_border         = '#322C44'
let g:foreglow_foreground     = '#E8E3F2'
let g:foreglow_foreground_dim = '#A49BBF'
let g:foreglow_comment        = '#736699'
let g:foreglow_keyword        = '#CB81E4'
let g:foreglow_string         = '#ED9F82'
let g:foreglow_function       = '#EC93BF'
let g:foreglow_number         = '#EFBF6C'
let g:foreglow_class          = '#75C6D7'
let g:foreglow_variable       = '#C7BCE6'
let g:foreglow_operator       = '#A085AD'
let g:foreglow_error          = '#E46772'
let g:foreglow_warning        = '#F2A65A'
let g:foreglow_success        = '#6BC7A8'
let g:foreglow_cursor         = '#F471C8'
